-- 80 preguntas nuevas para networking Perrenque (tono creativo, sin incomodidad).
-- Idempotente: no inserta si ya existe el mismo texto en la misma ronda.

INSERT INTO perrenque_preguntas (contenido, ronda, orden)
SELECT v.contenido, v.ronda::smallint, v.orden
FROM (
  VALUES
    -- Ronda 1 (40)
    ('¿Qué problema pequeño te gustaría resolver con creatividad si tuvieras un fin de semana libre?', 1, 5),
    ('Nombra un libro, charla o pieza que haya cambiado cómo ves tu trabajo.', 1, 6),
    ('¿Qué ritual tuyo (aunque sea sencillo) te ayuda a entrar en modo creativo?', 1, 7),
    ('Si pudieras aprender una técnica nueva en 30 días, ¿cuál elegirías y para qué?', 1, 8),
    ('¿Qué parte de tu proceso creativo te gustaría simplificar este año?', 1, 9),
    ('Cuéntale al grupo un proyecto que te enorgullezca sin usar títulos ni marcas.', 1, 10),
    ('¿Qué tendencia de tu industria te parece sobrevalorada — y cuál infravalorada?', 1, 11),
    ('Describe un “momento eureka” reciente, aunque haya sido en algo cotidiano.', 1, 12),
    ('¿Con qué tipo de feedback trabajas mejor: directo, con ejemplos o con preguntas?', 1, 13),
    ('¿Qué habilidad “blanda” crees que más diferencia a equipos creativos que rinden bien?', 1, 14),
    ('Si mañana presentaras una idea en 3 minutos, ¿sobre qué tema sería?', 1, 15),
    ('¿Qué aprendiste en el último proyecto que aplicarías desde el día uno en el siguiente?', 1, 16),
    ('Nombra un lugar (físico o digital) donde sueles encontrar buenas ideas.', 1, 17),
    ('¿Qué criterio usas para decir “esto ya está listo” y dejar de pulir?', 1, 18),
    ('Comparte una pregunta que te gustaría hacerle a un referente de tu campo.', 1, 19),
    ('¿Qué parte de colaborar con otros te energiza y cuál te exige más paciencia?', 1, 20),
    ('Si tuvieras que enseñar algo en un taller de 20 minutos, ¿qué enseñarías?', 1, 21),
    ('¿Qué hábito de consumo de información te está sirviendo y cuál quisieras recortar?', 1, 22),
    ('Cuéntale al grupo un fallo que te dejó una lección clara (sin dramatizar).', 1, 23),
    ('¿Qué significa para ti “buen gusto” en el contexto de tu trabajo?', 1, 24),
    ('¿Qué pregunta te harías antes de aceptar un nuevo proyecto o cliente?', 1, 25),
    ('Nombra una herramienta o método que adoptaste tarde y ahora no cambiarías.', 1, 26),
    ('¿Cómo defines el éxito de un proyecto cuando no hay métricas perfectas?', 1, 27),
    ('¿Qué tema te gustaría explorar fuera de tu zona habitual de trabajo?', 1, 28),
    ('Describe una colaboración ideal en tres palabras y una frase.', 1, 29),
    ('¿Qué te gustaría que el mundo entendiera mejor sobre lo que haces?', 1, 30),
    ('Si pudieras delegar una tarea repetitiva mañana, ¿cuál sería?', 1, 31),
    ('¿Qué señal te indica que un equipo está alineado antes de empezar a producir?', 1, 32),
    ('Comparte una recomendación concreta (podcast, newsletter, curso) que valga la pena.', 1, 33),
    ('¿Qué versión “mínima viable” de tu idea te animaría a mostrar esta semana?', 1, 34),
    ('¿Qué valor buscas priorizar: claridad, originalidad, velocidad o profundidad — y por qué?', 1, 35),
    ('Nombra un proyecto ajeno que hayas visto y te haya inspirado el enfoque.', 1, 36),
    ('¿Qué frontera entre disciplinas te parece la más fértil hoy?', 1, 37),
    ('¿Cómo celebras un cierre de etapa cuando el resultado fue bueno pero no perfecto?', 1, 38),
    ('¿Qué pregunta te ayuda a entender mejor las expectativas de un cliente o socio?', 1, 39),
    ('Si tuvieras que explicar tu trabajo a un niño de 10 años, ¿qué analogía usarías?', 1, 40),
    ('¿Qué “regla no escrita” de tu oficio te gustaría que todos conocieran?', 1, 41),
    ('¿Qué te gustaría co-crear con alguien de este grupo si surgiera la oportunidad?', 1, 42),
    ('¿Qué aprendizaje de otro campo (no el tuyo) aplicaste con buenos resultados?', 1, 43),
    ('Cierra con una pregunta abierta que quieras dejar sobre la mesa para el grupo.', 1, 44),

    -- Ronda 2 (40)
    ('¿Qué insight del día te quedó dando vueltas y por qué?', 2, 5),
    ('Nombra una conexión nueva que valga la pena cultivar y qué podrían construir juntos.', 2, 6),
    ('¿Qué idea escuchaste hoy que te gustaría desarrollar en versión propia?', 2, 7),
    ('¿Qué pregunta te hubiera gustado hacer en la primera ronda y ahora sí puedes hacerla?', 2, 8),
    ('Comparte un “antes y después” mental: ¿qué cambió en cómo ves tu proyecto o meta?', 2, 9),
    ('¿Qué recurso, contacto o dato concreto podrías ofrecer a alguien de la mesa?', 2, 10),
    ('¿Qué parte del evento superó tus expectativas y cuál te dejó con curiosidad?', 2, 11),
    ('Si armaras un mini-equipo con gente de aquí, ¿qué reto les propondrías?', 2, 12),
    ('¿Qué decisión pequeña tomarás esta semana gracias a algo que escuchaste hoy?', 2, 13),
    ('Nombra una práctica del networking que quieras mantener después de irte.', 2, 14),
    ('¿Qué tema del día te gustaría profundizar en una segunda conversación?', 2, 15),
    ('¿Cómo describirías el “clima” de tu grupo en una palabra y por qué?', 2, 16),
    ('¿Qué aprendiste de otro participante que no esperabas?', 2, 17),
    ('Si escribieras un titular sobre tu día aquí, ¿cuál sería (sin exagerar)?', 2, 18),
    ('¿Qué línea de trabajo tuya podría intersectar con la de alguien del grupo?', 2, 19),
    ('¿Qué feedback breve le darías a la organización para mejorar la experiencia?', 2, 20),
    ('Nombra una idea que al principio te sonó rara y ahora te parece interesante.', 2, 21),
    ('¿Qué pregunta te llevarías para tu próximo evento de networking?', 2, 22),
    ('¿Qué acuerdo informal (café, llamada, intercambio) te gustaría concretar?', 2, 23),
    ('¿Qué valor del evento —contenido, personas o formato— fue el más útil para ti?', 2, 24),
    ('Comparte una frase tuya que resume lo que te llevas (puede ser sencilla).', 2, 25),
    ('¿Qué bloqueo creativo mencionó alguien y qué ángulo nuevo viste al escucharlo?', 2, 26),
    ('¿Con qué perfil de este grupo te sentiste más afín y en qué se notó?', 2, 27),
    ('¿Qué te gustaría documentar o anotar antes de que se diluya la memoria del día?', 2, 28),
    ('Si tuvieras 15 minutos más con el grupo, ¿qué dinámica propondrías?', 2, 29),
    ('¿Qué promesa realista te haces a ti mismo para la semana que viene?', 2, 30),
    ('Nombra algo que hoy te recordó por qué te gusta lo que haces.', 2, 31),
    ('¿Qué diferencia notaste entre conectar “en frío” y conectar después de esta dinámica?', 2, 32),
    ('¿Qué proyecto o meta mencionó alguien y te gustaría seguir de lejos su avance?', 2, 33),
    ('¿Qué pregunta harías al grupo si pudieran responderte con total honestidad profesional?', 2, 34),
    ('¿Qué “puente” crearías entre dos ideas que escuchaste de personas distintas?', 2, 35),
    ('¿Qué señal te diría que hoy fue un buen uso de tu tiempo?', 2, 36),
    ('Comparte un elogio profesional concreto a alguien del grupo (sin presión).', 2, 37),
    ('¿Qué tema evitarías en un primer follow-up y cuál abrirías con entusiasmo?', 2, 38),
    ('¿Qué versión mejorada de tu pitch personal ensayarías antes del próximo evento?', 2, 39),
    ('¿Qué te llevas para contarle a alguien que no vino, en una oración?', 2, 40),
    ('¿Qué rol te gustó ocupar hoy en el grupo: impulsor, escucha, sintetizador u otro?', 2, 41),
    ('Nombra un próximo paso micro (mensaje, link, calendario) que harás en 48 horas.', 2, 42),
    ('¿Qué aprendizaje colectivo sintió el grupo —aunque sea una intuición?', 2, 43),
    ('Cierra agradeciendo algo específico del intercambio de hoy (idea, dato o actitud).', 2, 44)
) AS v(contenido, ronda, orden)
WHERE NOT EXISTS (
  SELECT 1 FROM perrenque_preguntas p WHERE p.contenido = v.contenido AND p.ronda = v.ronda::smallint
);
