-- 80 preguntas nuevas para networking Perrenque (tono creativo, sin incomodidad).
-- Idempotente: no inserta si ya existe el mismo texto en la misma ronda.
INSERT INTO perrenque_preguntas (contenido, ronda, orden)
SELECT v.contenido, v.ronda::smallint, v.orden
FROM (
  VALUES
    ('¿Qué te trajo hasta aquí hoy — y qué esperabas encontrar?', 1, 5),
    ('Si tu trabajo fuera un género musical, ¿cuál sería y por qué?', 1, 6),
    ('¿Cuál fue el último proyecto que te hizo perder la noción del tiempo?', 1, 7),
    ('¿Qué talento tuyo crees que la mayoría de las personas de tu industria no tienen?', 1, 8),
    ('Descríbete en tres palabras: una profesional, una personal, una que te sorprenda a ti mismo.', 1, 9),
    ('¿Cuál es la pregunta que más te hacen sobre tu trabajo — y cuál es la que deberían hacer?', 1, 10),
    ('¿Qué ciudad o lugar fuera de Barranquilla te ha inspirado profesionalmente?', 1, 11),
    ('¿Qué ritual tuyo (aunque sea sencillo) te ayuda a entrar en modo creativo?', 1, 12),
    ('¿Qué aprendiste en los últimos seis meses que no esperabas aprender?', 1, 13),
    ('¿Qué parte de tu trabajo no se puede automatizar — y cómo lo sabes?', 1, 14),
    ('¿Cuál es el mayor malentendido sobre lo que haces?', 1, 15),
    ('Si pudieras colaborar con alguien de otro campo completamente diferente al tuyo, ¿de qué campo sería?', 1, 16),
    ('¿Qué reto de tu trabajo también existe en la cocina, el deporte o el teatro?', 1, 17),
    ('¿Qué te hace quedarte en un proyecto más allá del plazo — y qué te hace soltarlo?', 1, 18),
    ('¿Cuándo fue la última vez que algo te pareció feo y después te pareció brillante?', 1, 19),
    ('¿Qué consejo recibiste que parecía obvio pero tardaste años en aplicar?', 1, 20),
    ('¿Qué necesitas de las personas con las que colaboras que pocas veces pides explícitamente?', 1, 21),
    ('¿Qué tendencia de tu industria adoptaste tarde — y por eso la entiendes mejor?', 1, 22),
    ('¿Qué habilidad de alguien que no es de tu campo te gustaría tener por un día?', 1, 23),
    ('Si tuvieras que enseñar algo en cinco minutos, ahora mismo, ¿qué elegirías?', 1, 24),
    ('¿Qué es lo primero que haces cuando un proyecto no arranca?', 1, 25),
    ('¿Qué pregunta de cliente o usuario te ha hecho repensar algo fundamental?', 1, 26),
    ('¿Cuál es tu filtro personal para decir que sí a algo nuevo?', 1, 27),
    ('¿Qué proyecto o idea tuya está todavía en modo borrador y merece salir?', 1, 28),
    ('¿Qué momento de tu carrera le contarías a alguien que apenas empieza?', 1, 29),
    ('¿Qué disciplina artística o creativa que no practicas te parece fascinante?', 1, 30),
    ('¿Cuál es tu indicador personal de que algo vale la pena — antes de ver resultados?', 1, 31),
    ('¿Qué truco mental usas cuando el bloqueo creativo aparece?', 1, 32),
    ('¿Qué cambió en tu forma de trabajar después de la pandemia que no vas a revertir?', 1, 33),
    ('¿Qué le dirías a alguien que empieza en tu campo que los manuales no dicen?', 1, 34),
    ('¿Qué tipo de feedback te cuesta más recibir — y cómo lo procesas?', 1, 35),
    ('¿Qué problema de tu ciudad o región te gustaría ver resuelto con creatividad?', 1, 36),
    ('¿Cuál es el recurso (libro, persona, espacio) que más ha formado tu gusto?', 1, 37),
    ('¿Qué proyecto te gustaría hacer que todavía no tienes el equipo o el presupuesto?', 1, 38),
    ('¿Qué diferencia a alguien bueno de alguien extraordinario en tu campo?', 1, 39),
    ('¿Qué parte de tu proceso nadie ve pero es la que más importa?', 1, 40),
    ('¿Qué te haría decir que este evento valió completamente el tiempo?', 1, 41),
    ('¿Qué conexión ideal te imaginas hacer antes de que termine el día?', 1, 42),
    ('¿Qué ofreces que pocos tienen y pocos saben que necesitan?', 1, 43),
    ('Cierra con algo que estés construyendo y en lo que genuinamente quieras opinión externa.', 1, 44),
    ('¿Qué conversación de hoy te quedó resonando — y qué parte te sorprendió?', 2, 5),
    ('¿A quién de este grupo le harías una pregunta de seguimiento esta semana?', 2, 6),
    ('¿Qué idea escuchaste que podrías llevar a tu trabajo sin adaptarla casi nada?', 2, 7),
    ('¿Qué cambió en cómo describes lo que haces después de escuchar a otros hoy?', 2, 8),
    ('¿Qué conexión entre dos personas del grupo ves tú que ellas quizás no vieron?', 2, 9),
    ('¿Qué ofreciste hoy — aunque sea en conversación — que no sueles ofrecer fácilmente?', 2, 10),
    ('¿Qué pregunta de la primera ronda te habría gustado responder diferente?', 2, 11),
    ('¿Con qué persona de hoy sientes que empezaste una conversación que merece continuar?', 2, 12),
    ('¿Qué aprendizaje de hoy aplicarías esta semana — en qué contexto específico?', 2, 13),
    ('¿Qué perfil de persona te falta en tu red y que tal vez encontraste aquí?', 2, 14),
    ('¿Qué idea del grupo te gustaría robar con permiso y por qué?', 2, 15),
    ('¿Qué hiciste en esta dinámica que no sueles hacer en eventos de networking tradicionales?', 2, 16),
    ('¿Qué incomodidad pequeña superaste hoy — al hablar, al escuchar, al compartir?', 2, 17),
    ('¿Qué le contarías a un amigo sobre este evento en tres oraciones?', 2, 18),
    ('¿Qué proyecto de alguien del grupo te merece seguimiento genuino — no por educación?', 2, 19),
    ('¿Qué perspectiva de otro campo cambió o amplió algo que dabas por sentado?', 2, 20),
    ('¿Qué conversación corta de hoy fue más densa de lo que parecía?', 2, 21),
    ('¿Qué rol tomaste naturalmente en el grupo — y es el que siempre tomas?', 2, 22),
    ('¿Qué acuerdo informal salió de esta ronda que merece convertirse en algo real?', 2, 23),
    ('¿Qué talento de alguien del grupo viste y que probablemente ellos subestiman?', 2, 24),
    ('¿Qué pregunta de otro participante también te aplica a ti — y no lo habías notado?', 2, 25),
    ('¿Qué fue más útil: lo que dijiste, lo que escuchaste, o lo que te preguntaron?', 2, 26),
    ('¿Qué seguiría pasando en esta mesa si les dieran 30 minutos más?', 2, 27),
    ('¿Qué promesa pequeña y concreta te haces antes de salir del evento?', 2, 28),
    ('¿Qué energía del grupo te gustaría llevarte a tu equipo o espacio de trabajo?', 2, 29),
    ('¿Qué mensaje enviarías a alguien del grupo antes de que termine la semana?', 2, 30),
    ('¿Qué viste en la dinámica que podría mejorar para la próxima edición?', 2, 31),
    ('¿Qué silencio del grupo fue más interesante que cualquier respuesta?', 2, 32),
    ('¿Qué pregunta de hoy reveló algo de ti que no esperabas compartir?', 2, 33),
    ('¿Qué idea del grupo merece un proyecto piloto — aunque sea muy pequeño?', 2, 34),
    ('¿Qué conectaste hoy entre tu trabajo y el de otro que no habías imaginado antes?', 2, 35),
    ('¿Qué es lo que más te costó responder hoy — y por qué crees que fue así?', 2, 36),
    ('¿Qué aprendiste del proceso de conocer personas en este formato versus uno libre?', 2, 37),
    ('¿Qué frase de alguien del grupo querrías tener escrita en algún lado?', 2, 38),
    ('¿Qué parte de tu trabajo explicaste mejor hoy que en cualquier pitch anterior?', 2, 39),
    ('¿Qué le agradeces al grupo, en específico — sin generalizar?', 2, 40),
    ('¿Qué próximo paso concreto tienes claro y cuál todavía está borroso?', 2, 41),
    ('¿Qué de este grupo te gustaría que Perrenque Creativo volviera a reunir — y para qué?', 2, 42),
    ('¿Qué intención te llevas que no traías cuando llegaste?', 2, 43),
    ('Cierra con algo genuino: lo que más valoras del intercambio de hoy, en una oración.', 2, 44)
) AS v(contenido, ronda, orden)
WHERE NOT EXISTS (
  SELECT 1 FROM perrenque_preguntas p WHERE p.contenido = v.contenido AND p.ronda = v.ronda::smallint
);